### ISSUE TITLE
I NEED HELP

### ISSUE THREAD

**Issue by Butter122** [zhenglab/FFDBackbone#2]
i can't download the flie named"BEiT_v2'',when  i got to your URL, it leads me to "BEiT-1k-Face-55w.tar"

**Comment by ouc-liuyingjie** [comment]
"BEiT-1k-Face-55w.tar" is a weight file pre-trained based on real faces. If you want to train a FFD model, please load this weight;
"Final mainbranch. tar" is a weight file trained on the FF++. If you want to perform inference or reproduce paper scores, please load this weight.

**Comment by Butter122** [comment]
我的代码会有这个报错：FileNotFoundError: [Errno 2] No such file or directory: 'Final-BEiT_v2.tar'

**Comment by ouc-liuyingjie** [comment]
请问你运行的哪个命令和文件会有这个报错？

**Comment by Butter122** [comment]
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11023 train_dualbranch.py -c configs/DBBF.yaml
而且您貌似不小心把BEiT_v2'的下载链接放错了

**Comment by ouc-liuyingjie** [comment]
抱歉，是utils\ckpt_process.py存在问题，已经完成修改了，您可以重新下载该文件后再尝试，十分感谢

**Comment by Butter122** [comment]
感谢您的回复，如果有问题我还会过来问您的

**Comment by Butter122** [comment]
您提供的环境安装指令貌似有很多问题，我运行后仍然提示缺少很多包

**Comment by ouc-liuyingjie** [comment]
您好，requirements.txt中提供了运行推理时所需的关键依赖。
为了方便您进行训练，已经重新上传requirements.txt，包含所需的全部环境，感谢您的提问。

**Comment by Butter122** [comment]
AssertionError: MMCV==0.6.2 is used but incompatible. Please install mmcv>=2.0.0, <2.4.0.
好像这个包有点老了
而且还不能装新版本（装了会报错）

**Comment by Butter122** [comment]
> AssertionError: MMCV==0.6.2 is used but incompatible. Please install mmcv>=2.0.0, <2.4.0. 好像这个包有点老了 而且还不能装新版本（装了会报错）

已经解决了

**Comment by Butter122** [comment]
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\13058\\Desktop\\FFDBackbone-main\\cfg.yaml'
缺少这个文件

**Comment by ouc-liuyingjie** [comment]
请问您是否调用命令时，正确地在”-c”参数中将yaml文件的地址传入，看起来您的报错是因为调用了默认的yaml配置文件。

**Comment by Butter122** [comment]
我尝试着把config/backbone/里面的resnet50.yaml改成DBBF.yaml报错说FileNotFoundError: [Errno 2] No such file or directory: '../data/FF++/face_v1/splits/train.json'

**Comment by ouc-liuyingjie** [comment]
> 我尝试着把config/backbone/里面的resnet50.yaml改成DBBF.yaml报错说FileNotFoundError: [Errno 2] No such file or directory: '../data/FF++/face_v1/splits/train.json'

您好，这说明程序已经成功运行到了数据加载的部分，由于数据集过大无法上传到代码仓库中，所以需要您根据您本地处理好的数据集的路径来修改dataset中相应的加载路径部分。

**Comment by Butter122** [comment]
这个train.json是放什么东西的呀

**Comment by ouc-liuyingjie** [comment]
json文件提供了FaceForensics++数据集中视频的ID相关信息，
您可以参考FaceForensics++数据集的公开代码库：https://github.com/ondyari/FaceForensics/tree/master/dataset/splits

**Comment by Butter122** [comment]
如果我们只是要运行代码进行预测而非训练，这个train.json有用吗

**Comment by ouc-liuyingjie** [comment]
您好，train.json是用于模型训练时，加载FF++的训练集的，
如果只是预测单个视频，直接运行  python Inference.py；
如果评估FF++的测试集的分数（预测数据集内每一个视频），需要FF++的test.json;
如果评估其他数据集的分数，需要您对不同的数据集进行划分和预处理后，修改相应的加载数据的路径。
