### ISSUE TITLE
I need help too!

### ISSUE THREAD

**Issue by CUPLC** [zhenglab/FFDBackbone#3]
FileNotFoundError: [Errno 2] No such file or directory: '../datasets_processed_8frames/FF_frames/face_v1/splits/test.json'
I run eval.py with the given command 'CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --master_port 11011 eval.py -c checkpoints/Ours/DBBF.yaml' and got this error. I find that there's no such directory in your github, what do I need to do to get this directory or could you provide this directory as an example?

**Comment by Butter122** [comment]
I MET THIS PROBLEM TOO! LOL

**Comment by CUPLC** [comment]
I'm so stupid that I never find it

**Comment by ouc-liuyingjie** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '../datasets_processed_8frames/FF_frames/face_v1/splits/test.json' I run eval.py with the given command 'CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --master_port 11011 eval.py -c checkpoints/Ours/DBBF.yaml' and got this error. I find that there's no such directory in your github, what do I need to do to get this directory or could you provide this directory as an example?

Hello, the evaluation requires cropped and aligned dataset, but the dataset is too large to be uploaded to the repositories. You can modify the dataset data loading path and method according to your local dataset address. Or you can call “inference.py” to infer the video according to your local data loading method.
