### ISSUE TITLE
Request to make weights available on other platforms

### ISSUE THREAD

**Issue by pyesonekyaw** [zhenglab/FFDBackbone#4]
Could you provide the weights on other platforms like Google Drive or OneDrive? I'm not able to download from BaiduPan

**Comment by ouc-liuyingjie** [comment]
Hello, the link to Google Cloud Disk is as follows:
https://drive.google.com/drive/folders/1jFIpb4TftJiL82h69c3Roqy8uIzGQP4G?usp=sharing

**Comment by pyesonekyaw** [comment]
Thank you very much!
